<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../Src/APIGateway.Proxy/APIGateway.Proxy.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../../Src/APIGateway.Proxy/appsettings.json" Link="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>