name: Release and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger PAT access request
        run: |
          curl -s -H "Authorization: token ${{ secrets.PAT }}" \
                https://api.github.com/repos/${{ github.repository }}

      - name: Set up go-semantic-release
        uses: go-semantic-release/action@v1.24.1
        with:
            github-token: ${{ secrets.PAT }}
            allow-initial-development-versions: true

      - name: Get next version
        id: get_version
        run: |
          VERSION=$(go-semantic-release version --print | jq -r .next)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        

  docker:
    runs-on: ubuntu-latest
    needs: semver
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and Push Image to GHCR
        run: |
          VERSION=${{ needs.semver.outputs.version }}
          IMAGE=ghcr.io/${{ github.repository_owner }}/api-gateway 

          docker build -t $IMAGE:$VERSION .
          docker tag $IMAGE:$VERSION $IMAGE:latest

          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest
